apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://grafana-community.github.io/helm-charts
      chart: alloy
      targetRevision: "*"
      helm:
        valueFiles:
          - $values/observability/alloy/alloy-values.yaml    
  - repoURL: https://github.com/bartasp/argocd-lab.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
