resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    memory: 512Mi

livenessProbe:
  initialDelaySeconds: 120
  timeoutSeconds: 10
  failureThreshold: 6

readinessProbe:
  initialDelaySeconds: 60
  timeoutSeconds: 10
  failureThreshold: 6
persistence:
  enabled: true
  size: 1Gi

service:
  type: NodePort
  nodePort: 30300

adminPassword: "admin123"

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        url: http://loki.observability.svc.cluster.local:3100
        access: proxy
      - name: Mimir
        type: prometheus
        url: http://mimir-nginx.observability.svc.cluster.local/prometheus
        access: proxy
      - name: Tempo
        type: tempo
        url: http://tempo.observability.svc.cluster.local:3100
        access: proxy
