mimir:
  structuredConfig:
    limits:
      compactor_blocks_retention_period: 6h
      ingestion_rate: 10000
      ingestion_burst_size: 20000

minio:
  enabled: true
  persistence:
    size: 1Gi
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      memory: 128Mi

nginx:
  enabled: true
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      memory: 64Mi
  config:
    dnsResolver: rke2-coredns-rke2-coredns.kube-system.svc.cluster.local

alertmanager:
  enabled: false

ruler:
  enabled: false

overrides_exporter:
  enabled: false

compactor:
  replicas: 1
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      memory: 128Mi
  persistentVolume:
    size: 1Gi

distributor:
  replicas: 1
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      memory: 128Mi

ingester:
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 256Mi
  persistentVolume:
    size: 1Gi

querier:
  replicas: 1
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      memory: 128Mi

query_frontend:
  replicas: 1
  resources:
    requests:
      cpu: 15m
      memory: 32Mi
    limits:
      memory: 64Mi

query_scheduler:
  replicas: 1
  resources:
    requests:
      cpu: 15m
      memory: 32Mi
    limits:
      memory: 64Mi

store_gateway:
  replicas: 1
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      memory: 128Mi
  persistentVolume:
    size: 1Gi

metaMonitoring:
  serviceMonitor:
    enabled: false
