mimir:
  structuredConfig:
    limits:
      compactor_blocks_retention_period: 24h

minio:
  enabled: true
  persistence:
    size: 2Gi
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 256Mi

nginx:
  config:
    dnsResolver: rke2-coredns-rke2-coredns.kube-system.svc.cluster.local
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 128Mi

alertmanager:
  replicas: 1
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      memory: 128Mi
  persistentVolume:
    size: 1Gi

compactor:
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 256Mi
  persistentVolume:
    size: 2Gi

distributor:
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 256Mi

ingester:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi
  persistentVolume:
    size: 2Gi

querier:
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 256Mi

query_frontend:
  replicas: 1
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      memory: 128Mi

query_scheduler:
  replicas: 1
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      memory: 128Mi

store_gateway:
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 256Mi
  persistentVolume:
    size: 2Gi

ruler:
  enabled: false

overrides_exporter:
  enabled: false

metaMonitoring:
  serviceMonitor:
    enabled: false
